<a href="https://colab.research.google.com/github/qjpbtuzara-ai/CPE311-CPE22S3/blob/main/Copy_of_Tuzara_HOA8_1ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Tuzara, John Paul B. <br>
Course and Section: CPE311 - CPE22S3 <br>
Date: 3/2/2026 <br>
Instructor: Engr. Neal Barton James Matira

# Hands-on Activity 8.1: Aggregating Data with Pandas

### 8.1.1 Intended Learning Outcomes
After this activity, the student should be able to:
* Demonstrate querying and merging of dataframes
* Perform advanced calculations on dataframes
* Aggregate dataframes with pandas and numpy
* Work with time series data

### 8.1.2 Resources
* Computing Environment using Python 3.x
* Attached Datasets (under Instructional Materials)

### 8.1.3 Procedures
The procedures can be found in the canvas module. Check the following under topics:
* 8.1 Weather Data Collection
* 8.2 Querying and Merging
* 8.3 Dataframe Operations
* 8.4 Aggregations
* 8.5 Time Series

### 8.1.4 Data Analysis
> Provide some comments here about the results of the procedures.

### 8.1.5 Supplementary Activity

Using the CSV files provided and what we have learned so far in this module, complete the following exercises:

**1.** With the `earthquakes.csv` file, select all the earthquakes in Japan with a `magType` of `mb` and a magnitude of $4.9$ or greater.

In [ ]:
import numpy as np
import pandas as pd


earthquakes = pd.read_csv('earthquakes.csv')

# 1. Japan earthquakes with magType 'mb' and magnitude >= 4.9
japan_quakes = earthquakes[
    (earthquakes.parsed_place == 'Japan') &
    (earthquakes.magType == 'mb') &
    (earthquakes.mag >= 4.9)
]
japan_quakes

,mag,magType,time,place,tsunami,parsed_place
1563,4.9,mb,1538977532250,"293km ESE of Iwo Jima, Japan",0,Japan
2576,5.4,mb,1538697528010,"37km E of Tomakomai, Japan",0,Japan
3072,4.9,mb,1538579732490,"15km ENE of Hasaki, Japan",0,Japan
3632,4.9,mb,1538450871260,"53km ESE of Hitachi, Japan",0,Japan

**2.** Create bins for each full number of magnitude (for example, the first bin is 0-1, the second is 1-2, and so on) with a `magType` of `ml` and count how many are in each bin.

In [ ]:
# 2. Bins for magnitude with magType 'ml'
ml_quakes = earthquakes[earthquakes.magType == 'ml']
mag_bins = pd.cut(ml_quakes.mag, bins=np.arange(0, 10))
mag_bins.value_counts()

mag
(1, 2]    3105
(0, 1]    2207
(2, 3]     862
(3, 4]     122
(4, 5]       2
(5, 6]       1
(6, 7]       0
(7, 8]       0
(8, 9]       0
Name: count, dtype: int64

**3.** Using the `faang.csv` file, group by the ticker and resample to monthly frequency. Make the following aggregations:
* Mean of the opening price
* Maximum of the high price
* Minimum of the low price
* Mean of the closing price
* Sum of the volume traded

In [ ]:
faang = pd.read_csv('faang.csv')

faang['date'] = pd.to_datetime(faang['date'])

faang.set_index('date', inplace=True)

faang_monthly = faang.groupby('ticker').resample('M').agg({
    'open': 'mean',
    'high': 'max',
    'low': 'min',
    'close': 'mean',
    'volume': 'sum'
})

faang_monthly.head()

/tmp/ipython-input-379/1815752439.py:7: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  faang_monthly = faang.groupby('ticker').resample('M').agg({

                         open      high       low       close     volume
ticker date
AAPL   2018-01-31  170.714690  176.6782  161.5708  170.699271  659679440
       2018-02-28  164.562753  177.9059  147.9865  164.921884  927894473
       2018-03-31  172.421381  180.7477  162.4660  171.878919  713727447
       2018-04-30  167.332895  176.2526  158.2207  167.286924  666360147
       2018-05-31  182.635582  187.9311  162.7911  183.207418  620976206

**4.** Build a crosstab with the earthquake data between the `tsunami` column and the `magType` column.
* Rather than showing the frequency count, show the maximum magnitude that was observed for each combination.
* Put the `magType` along the columns.

In [ ]:
pd.crosstab(
    index=earthquakes.tsunami,
    columns=earthquakes.magType,
    values=earthquakes.mag,
    aggfunc='max'
)

magType   mb  mb_lg    md   mh   ml  ms_20    mw  mwb  mwr  mww
tsunami
0        5.6    3.5  4.11  1.1  4.2    NaN  3.83  5.8  4.8  6.0
1        6.1    NaN   NaN  NaN  5.1    5.7  4.41  NaN  NaN  7.5

**5.** Calculate the rolling 60-day aggregations of OHLC data by ticker for the FAANG data.
* Use the same aggregations as exercise no. 3.

In [ ]:
faang_rolling = faang.groupby('ticker').rolling('60D').agg({
    'open': 'mean',
    'high': 'max',
    'low': 'min',
    'close': 'mean',
    'volume': 'sum'
})
faang_rolling

                         open      high       low       close       volume
ticker date
AAPL   2018-01-02  166.927100  169.0264  166.0442  168.987200   25555934.0
       2018-01-03  168.089600  171.2337  166.0442  168.972500   55073833.0
       2018-01-04  168.480367  171.2337  166.0442  169.229200   77508430.0
       2018-01-05  168.896475  172.0381  166.0442  169.840675  101168448.0
       2018-01-08  169.324680  172.2736  166.0442  170.080040  121736214.0
...                       ...       ...       ...         ...          ...
NFLX   2018-12-24  283.509250  332.0499  233.6800  281.931750  525657894.0
       2018-12-26  281.844500  332.0499  231.2300  280.777750  520444588.0
       2018-12-27  281.070488  332.0499  231.2300  280.162805  532679805.0
       2018-12-28  279.916341  332.0499  231.2300  279.461341  521968250.0
       2018-12-31  278.430769  332.0499  231.2300  277.451410  476309676.0

[1255 rows x 5 columns]

**6.** Create a pivot table of the FAANG data that compares the stocks.
* Put the ticker in the rows and show the averages of the OHLC and volume traded data.

In [ ]:
faang.pivot_table(
    index='ticker',
    values=['open', 'high', 'low', 'close', 'volume'],
    aggfunc='mean'
)

              close         high          low         open        volume
ticker
AAPL     186.986218   188.906858   185.135729   187.038674  3.402145e+07
AMZN    1641.726175  1662.839801  1619.840398  1644.072669  5.649563e+06
FB       171.510936   173.615298   169.303110   171.454424  2.768798e+07
GOOG    1113.225139  1125.777649  1101.001594  1113.554104  1.742645e+06
NFLX     319.290299   325.224583   313.187273   319.620533  1.147030e+07

**7.** Calculate the Z-scores for each numeric column of Netflix's data (ticker is `NFLX`) using `apply()`.

In [ ]:
netflix_data = faang[faang.ticker == 'NFLX']
netflix_zscores = netflix_data.select_dtypes(include=[np.number]).apply(
    lambda x: (x - x.mean()) / x.std()
)
netflix_zscores.head()

**8. Add event descriptions:**
* Create a dataframe with the following three columns: `ticker`, `date`, and `event`.
    * **ticker:** 'FB'
    * **date:** `['2018-07-25', '2018-03-19', '2018-03-20']`
    * **event:** `['Disappointing user growth announced after close.', 'Cambridge Analytica story', 'FTC investigation']`
* Set the index to `['date', 'ticker']`
* Merge this data with the FAANG data using an outer join

In [ ]:
events = pd.DataFrame({
    'ticker': 'FB',
    'date': pd.to_datetime(['2018-07-25', '2018-03-19', '2018-03-20']),
    'event': [
        'Disappointing user growth announced after close.',
        'Cambridge Analytica story',
        'FTC investigation'
    ]
}).set_index(['date', 'ticker'])

faang_indexed = faang.reset_index().set_index(['date', 'ticker'])
faang_with_events = faang_indexed.join(events, how='outer')
faang_with_events.loc['2018-03-19':'2018-03-20']

                        open       high        low      close     volume  \
date       ticker
2018-03-19 AAPL     174.6604   174.8081   171.0553   172.6707   33446771
           AMZN    1554.5300  1561.6600  1525.3500  1544.9300    6580766
           FB       177.0100   177.1700   170.0600   172.5600   88140060
           GOOG    1120.0100  1121.9900  1089.0100  1099.8200    2805937
           NFLX     315.8000   317.0000   307.3400   313.4800    9925162
2018-03-20 AAPL     172.6116   174.1482   172.3161   172.6116   19649350
           AMZN    1550.3400  1587.0000  1545.4100  1586.5100    4581568
           FB       167.4700   170.2000   161.9500   168.1500  129851768
           GOOG    1099.0000  1105.2000  1083.4600  1097.7100    1831896
           NFLX     313.2600   319.5000   312.8000   317.5000    5991945

                                       event
date       ticker
2018-03-19 AAPL                          NaN
           AMZN                          NaN
           FB      Cambridge Analytica story
           GOOG                          NaN
           NFLX                          NaN
2018-03-20 AAPL                          NaN
           AMZN                          NaN
           FB              FTC investigation
           GOOG                          NaN
           NFLX                          NaN

**9.** Use the `transform()` method on the FAANG data to represent all the values in terms of the first date in the data.
* To do so, divide all the values for each ticker by the values for the first date in the data for that ticker.
* This is referred to as an index, and the data for the first date is the base.
* **Hint:** `transform()` can take a function name.

In [ ]:
faang_index = faang.groupby('ticker').transform(lambda x: x / x.iloc[0])
faang_index.head()

                open      high       low     close    volume
date
2018-01-02  1.000000  1.000000  1.000000  1.000000  1.000000
2018-01-03  1.023638  1.017623  1.021290  1.017914  0.930292
2018-01-04  1.040635  1.025498  1.036889  1.016040  0.764707
2018-01-05  1.044518  1.029298  1.041566  1.029931  0.747830
2018-01-08  1.053579  1.040313  1.049451  1.037813  0.991341